Category.find_or_create_by!(name: "Rails")
Category.find_or_create_by!(name: "JavaScript")
Category.find_or_create_by!(name: "HTML/CSS")
Category.find_or_create_by!(name: "SQL")
Category.find_or_create_by!(name: "Git")
Category.find_or_create_by!(name: "転職活動")
Category.find_or_create_by!(name: "その他")
